### ISSUE TITLE
Flavor Text does not open

### ISSUE THREAD

**Issue by Hardly3D** [DaedalusDock/daedalusdock#927] opened 2024-05-05 20:47 UTC
## Testmerges:
[#917: 'Adds a Guest Mode' by Kapu1178 at commit 831af19afe](https://github.com/DaedalusDock/Gameserver/pull/917)
[#909: 'Split brained tgui' by francinum at commit 12f18b84bf](https://github.com/DaedalusDock/Gameserver/pull/909)
[#923: 'Debug reboot failures' by Kapu1178 at commit f2da38c625](https://github.com/DaedalusDock/Gameserver/pull/923)
[#921: 'fix hand item bug' by Kapu1178 at commit d1425298f4](https://github.com/DaedalusDock/Gameserver/pull/921)

## Reproduction:
Examine someone, try to open their flavor text only for the pop up not to open at all

**Comment by francinum** [comment] 2024-08-28 01:33
Duplicate of #767

**Closed by francinum** 2024-08-28 01:33 UTC
